name: Auto-merge PRs after approval

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
